### ISSUE TITLE
Add option to 'publish' to add metadata

### ISSUE THREAD

**Issue by robertberrington** [doorstop-dev/doorstop#151]
I'd like the ability to add any metadata for which I have properties defined to the output. Also, order matters.

example:

```
  UID
  Text
  Links
  Rationale
  General Comments
```
##

**Comment by patkan** [comment]
I would like to try and implement this feature, but am unsure on how to do this.
Would it maybe be helpful to define the attributes in `.doorstop.yml` together with a name? I imagine an entry like this:

```
settings:
    ....
extra-attributes:
   rationale: Rationale
   general_comment: General Comments
```

Publish would then add these attributes to the output if it is set in the respective item.
If I understand the code right, the functions `_lines_markdown`, `_lines_text` and `_lines_html` in `publisher.py` would have to be modified.

Maybe you can give me some pointers and I will see if I can file a pull request in which we can iterate.
