### ISSUE TITLE
External reference not found:  F_allocation.csv

### ISSUE THREAD

**Issue by sevendays** [doorstop-dev/doorstop#479]
I'm trying to use the new `references` behaviour as described in the wiki: https://doorstop.readthedocs.io/en/latest/reference/item/#references-new-array-behavior

My requirement is:

```
active: true
derived: false
header: ''
level: 1.1.1
links:
- PRJ02: ZhhHI6cybMRVdVtgPToHqiAPERFx2O6FtdTjT4JIV_4=
normative: true
ref: ''
references:
- keyword: '#F001'
  path: F_allocation.csv
  type: file
reviewed: Ge91zi0XKSRDFfr7HqBE1EPQnSQZsiXz0aC0GzTEUBU=
safety: 0
text: |
  SOMETHING
```

The file `F_allocation.csv` is in the git repository root (I have tried both `/` and `\` for relative paths). 

Running `doorstop` raises no errors, and draws the requirement tree.

However, running `doorstop publish F Fmd` crashes.
