### ISSUE TITLE
Array references not working on Windows

### ISSUE THREAD

**Issue by knightofni-i** [doorstop-dev/doorstop#495]
The "self." is missing from the fourth argument (`self.path`) of the following call in `item.py`
```
reference = self.reference_finder.find_file_reference(
                path, self.root, self.tree, self.path, keyword
            )
```
Additionally, the following approach is suggested for line 73 of reference_finder.py
```
ref_full_path = os.path.abspath(os.path.join(root, ref_path))
```
Using Windows, `path == ref_full_path` doesn't always work unless you use abspath because relative references can result in `\\.\\` being in the path.

This approach was tested using a test file with:
```
references:
- path: tests\\test_filename.py
  type: file
  keyword: test_name_here
- path: tests\\test_filename.py
  type: file
  keyword: test_name2_here
```
