### ISSUE TITLE
Missing documentation for publishing custom attributes

### ISSUE THREAD

**Issue by akuker-in-advantage** [doorstop-dev/doorstop#694]
I haven't been able to find any documentation on how to publish the custom doorstop attributes.

Recommend updating this page: https://doorstop.readthedocs.io/en/stable/cli/publishing.html

With an example for outputting additional attributes.

Here is my example `.doorstop.yml`
```
settings:
  digits: 3
  prefix: SYSTEM-REQ
  sep: '-'
attributes:
  publish: 
    - commentary
    - rationale
 ```

This results in these two attributes being published in a table below the requirement itself (for the html report)
