### ISSUE TITLE
Doc Title in attributes->default

### ISSUE THREAD

**Issue by obruendl** [doorstop-dev/doorstop#701]
I found out that I have to set the output document title using _attributes->defaults->doc->title_:

```
settings:
  digits: 1
  itemformat: yaml
  prefix: SWLH
  sep: '-'
attributes:
  defaults:
    doc:
      title: '<my-document-title>
```

However, this leads to all new items having this property because it is a default. Is there any way I can set the document title in the documents YAML without having it added to all child items? IMO it is needless to replicate the title into all requirement items.
